
import { 
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious
} from "@/components/ui/carousel";
import { Card, CardContent } from "@/components/ui/card";
import { Star } from "lucide-react";

export function Testimonials() {
  const testimonials = [
    {
      quote: "ClipFarm has transformed how I repurpose my content. What used to take hours now happens automatically, and the results are incredible!",
      author: "Alex Johnson",
      role: "YouTube Creator, 500K subscribers",
      stars: 5
    },
    {
      quote: "The AI caption generator is a game-changer. My engagement rates have gone up by 45% since I started using ClipFarm for my content strategy.",
      author: "Maya Williams",
      role: "Content Creator & Influencer",
      stars: 5
    },
    {
      quote: "As a social media manager handling multiple channels, ClipFarm has been a lifesaver. The automatic editing saves me hours every week.",
      author: "Daniel Rodriguez",
      role: "Social Media Director",
      stars: 5
    },
    {
      quote: "The quality of shorts generated by ClipFarm is consistently professional. It's like having a video editor on my team 24/7.",
      author: "Sarah Chen",
      role: "Business Coach & Speaker",
      stars: 5
    }
  ];

  return (
    <section id="testimonials" className="py-24 bg-gradient-to-b from-white to-gray-50">
      <div className="container">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-3xl md:text-4xl font-bold mb-6">Loved By Content Creators</h2>
          <p className="text-xl text-gray-600">
            See why thousands of creators trust ClipFarm to maximize their content strategy.
          </p>
        </div>
        
        <Carousel className="max-w-5xl mx-auto">
          <CarouselContent>
            {testimonials.map((testimonial, index) => (
              <CarouselItem key={index} className="sm:basis-1/1 md:basis-1/2 lg:basis-1/2 p-2">
                <Card className="border-0 shadow-lg h-full">
                  <CardContent className="p-8 h-full flex flex-col">
                    <div className="flex mb-4">
                      {[...Array(testimonial.stars)].map((_, i) => (
                        <Star key={i} className="h-5 w-5 text-yellow-500 fill-yellow-500" />
                      ))}
                    </div>
                    <blockquote className="text-lg text-gray-700 italic mb-6 flex-grow">
                      "{testimonial.quote}"
                    </blockquote>
                    <div>
                      <div className="font-semibold">{testimonial.author}</div>
                      <div className="text-gray-500 text-sm">{testimonial.role}</div>
                    </div>
                  </CardContent>
                </Card>
              </CarouselItem>
            ))}
          </CarouselContent>
          <div className="mt-8 flex justify-center gap-2">
            <CarouselPrevious className="relative static transform-none" />
            <CarouselNext className="relative static transform-none" />
          </div>
        </Carousel>
      </div>
    </section>
  );
}
